version: '2'
services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: python3 bot.py

  redis:
    restart: always
    image: redis:latest

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx_static:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"