version: '2'
services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: python3 bot.py

  coolq:
    restart: always
    image: richardchien/cqhttp:latest
    environment:
      - FORCE_ENV=true
      - COOLQ_WS_REVERSE_API_URL=ws://bot:8080/ws/api/
      - COOLQ_WS_REVERSE_EVENT_URL=ws://bot:8080/ws/event/
      - COOLQ_USE_WS_REVERSE=yes
      - COOLQ_ACCOUNT=732599980
      - VNC_PASSWD=qwer1234
    volumes:
      - ./cq:/home/user/coolq
    ports:
      - "9000:9000"
      - "5700:5700"

