version: '3'
services:
  gocqhttp:
    image: silicer/go-cqhttp
    volumes:
    - ./gocqhttp_data:/data
    depends_on:
      - bot

  bot:
    restart: always
    build: ./mynonebot
    volumes:
      - ./mynonebot:/app
    ports:
      - "8080:8080"
    command: python3 bot.py